name: Ping CI
# This workflow is triggered at scheduled intervals between 07:00-20:59 EST and 08:00-21:59 EDT
on:
  schedule:
    - cron:  '4,12,21,30,39,48,56 0-2,12-23 * * *'

jobs:
  ping:
    name: Ping app
    runs-on: ubuntu-latest
    env:
      URL: https://markobuha.ca
      METHOD: GET  # the method used to make the request. It is GET by default
    steps:
      - name: Ping
        uses: sisodiya2421/pinger@master
