name: Ping CI
# This workflow is triggered at a scheduled interval of every 9 minutes between 07:00-20:59 EST and 08:00-21:59 EDT
on:
  schedule:
    # * is a special character in YAML so you have to quote this string.
    # /9 denotes that it will run once every 9 minutes
    - cron:  '*/5 0-2,12-23 * * *'

jobs:
  ping:
    name: Ping app
    runs-on: ubuntu-latest
    env:
      URL: https://markobuha.ca
      METHOD: GET  # the method used to make the request. It is GET by default
    steps:
      - name: Ping
        uses: sisodiya2421/pinger@master
