name: Ping CI
# This workflow is triggered at scheduled intervals between 07:00-20:59 EST and 08:00-21:59 EDT
on:
  schedule:
    - cron:  '3,9,15,21,27,33,39,45,51,57 0-2,12-23 * * *'

jobs:
  ping:
    name: Ping app
    runs-on: ubuntu-latest
    env:
      URL: https://markobuha.ca
      METHOD: GET  # the method used to make the request. It is GET by default
    steps:
      - name: Ping
        uses: sisodiya2421/pinger@master
